# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '80cec882-05c2-4cca-9849-9807fe9055e0'
  imageRepository: 'somuvotingapp'
  containerRegistry: 'somuacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  # vmImageName: 'somuba'

#***************************************************************************************
#                        BUILD STAGE
#***************************************************************************************

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: somu agent pool
      demands:
        - Agent.Name -equals somuba
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

#***************************************************************************************
#                        PUSH STAGE
#***************************************************************************************          

- stage: Push
  displayName: Push Stage
  jobs:
  - job: Push
    displayName: Push Image to ACR
    pool:
      name: somu agent pool
      demands:
        - Agent.Name -equals somuba
    steps:
    - task: Docker@2
      displayName: Push an image to ACR
      inputs:
        command: push
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

#***************************************************************************************
#                        DEPLOY STAGE
#***************************************************************************************          
- stage: DeployToVM
  displayName: "Deploy container image to VM"
  dependsOn: Push
  jobs:
  - deployment: VMDeploy
    displayName: "Deploy image from ACR to VM"
    environment: 'production'   # optional, can be any environment name
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              #azureSubscription: 'a4d417d6-4b7d-4dbc-8702-15f88c83dc21'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Logging into ACR..."
                az acr login --name somuacr
                echo "Pulling image..."
                docker pull somuacr.azurecr.io/somuvotingapp:$(Build.BuildId)
                echo "Deploying image to VM..."
                az vm run-command invoke \
                  --resource-group somumh \
                  --name somuba \
                  --command-id RunShellScript \
                  --scripts "docker run -d -p 5050:80 somuacr.azurecr.io/somuvotingapp:$(Build.BuildId)"